# Load directly from ../data, so this script can be run immediately after
# updating the candidates data, without reinstalling the package
load('../data/candidates.rda')
data('state_ids', package = 'elections')
data('county_ids', package = 'elections')

precinct_validity = list(
  year = list(
    type = 'integer',
    no_na = TRUE,
    n_unique = 1,
    values = seq.int(1976, 2018, 2)),
  stage = list(
    type = 'character',
    no_na = TRUE,
    n_unique = 1,
    values = c('gen', 'pri')),
  special = list(
    type = 'logical',
    no_na = TRUE),
  state = list(
    type = 'character',
    no_na = TRUE,
    n_unique = 1,
    values = state_ids$state),
  state_postal = list(
    type = 'character',
    no_na = TRUE,
    n_unique = 1,
    values = state_ids$state_postal),
  state_fips = list(
    type = 'integer',
    no_na = TRUE,
    n_unique = 1,
    values = state_ids$state_fips),
  state_icpsr = list(
    type = 'integer',
    no_na = TRUE,
    n_unique = 1,
    values = state_ids$state_icpsr),
  county_name = list(
    type = 'character',
    no_na = TRUE,
    values = county_ids$county_name),
  county_fips = list(
    type = 'integer',
    no_na = TRUE,
    values = type.convert(county_ids$county_fips)),
  county_ansi = list(
    type = 'integer',
    no_na = TRUE,
    values = type.convert(county_ids$county_ansi)),
  county_lat = list(
    type = 'numeric',
    no_na = TRUE,
    values = county_ids$county_lat),
  county_long = list(
    type = 'numeric',
    no_na = TRUE,
    values = county_ids$county_long),
  jurisdiction = list(
    type = 'character',
    no_na = TRUE,
    is_valid = function(s) {stringr::str_length(s) > 0}),
  precinct = list(
    type = 'character',
    no_na = FALSE),
  candidate = list(
    type = 'character',
    no_na = FALSE),
  candidate_last = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_last))),
  candidate_first = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_first))),
  candidate_middle = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_middle))),
  candidate_full = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_full))),
  candidate_suffix = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_suffix))),
  candidate_nickname = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_nickname))),
  candidate_normalized = list(
    type = 'character'),
  candidate_fec = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_fec))),
  candidate_fec_name = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_fec_name))),
  candidate_google = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_google))),
  candidate_govtrack = list(
    type = 'integer',
    values = c(NA, unique(candidates$candidate_govtrack))),
  candidate_icpsr = list(
    type = 'integer',
    values = c(NA, unique(candidates$candidate_icpsr))),
  candidate_maplight = list(
    type = 'integer',
    values = c(NA, unique(candidates$candidate_maplight))),
  candidate_opensecrets = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_opensecrets))),
  candidate_wikidata = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_wikidata))),
  candidate_party = list(
    type = 'character',
    values = c(NA, unique(candidates$candidate_party))),
  office = list(
    type = 'character'),
  district = list(
    type = 'character'),
  writein = list(
    type = 'logical',
    no_na = TRUE),
  party = list(
    type = 'character'),
  mode = list(
    type = 'character',
    no_na = TRUE),
  votes = list(
    type = 'integer',
    no_na = TRUE,
    is_valid = function(x) {
      x >= 0 & x %% 1 == 0
    }),
  dataverse = list(
    type = 'character',
    no_na = TRUE,
    values = c('president', 'senate', 'house', 'state', 'local', 'all')))

devtools::use_data(precinct_validity, overwrite = TRUE)

precinct_columns = names(precinct_validity)
devtools::use_data(precinct_columns, overwrite = TRUE)
